/**
 * DB_Diff_Checker_GUI is a JFrame that takes user input to decide which JFrame 
 * to open
 * @author Peter Kaufman
 * @class DB_Diff_Checker_GUI
 * @access public
 * @version 9-21-17
 * @since 9-20-17 
 */
package db_diff_checker_GUI;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
public class DB_Diff_Checker_GUI extends javax.swing.JFrame {

    /**
     * Creates new form DB_Diff_Checker_GUI
     * @author Peter Kaufman
     * @type constructor
     * @access public
     */
    public DB_Diff_Checker_GUI() {
        
        initComponents();
        this.setIconImage( new ImageIcon( getClass().getResource( "/Images/DBCompare.png" )).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Start = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        jContinue = new javax.swing.JButton();

        Start.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout StartLayout = new javax.swing.GroupLayout(Start.getContentPane());
        Start.getContentPane().setLayout(StartLayout);
        StartLayout.setHorizontalGroup(
            StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        StartLayout.setVerticalGroup(
            StartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Database Difference Checker");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(200, 200));
        setMinimumSize(new java.awt.Dimension(100, 50));
        setName("Start"); // NOI18N

        jLabel1.setText("1-Database compare using 2 database connections");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Database Options");

        jLabel3.setText("2-Database compare using 1 database connection");

        jLabel4.setText("3-Take database snapshot using 1 database connection");

        jLabel5.setText("Enter method to use:");

        jContinue.setText("Continue");
        jContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jContinueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jContinue)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jContinue))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * jContinueMouseClicked determines which JFrame to open based on user input
     * @author Peter Kaufman
     * @type function
     * @access public
     * @param evt is a MouseEvent which represents continue being clicked
     */
    private void jContinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jContinueMouseClicked

        if ( input.getText().trim().equals( "1" )) {
        
            DBCompare2 compare2DBS = new DBCompare2(); 
            compare2DBS.setSize( 575, 325 );
            compare2DBS.setVisible( true );
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        } else if ( input.getText().trim().equals( "2" )) {
        
            DBCompare1 compare1DB_DBSnapshot = new DBCompare1();
            compare1DB_DBSnapshot.setSize( 350 , 275 );
            compare1DB_DBSnapshot.setButtonTxt( "Compare" );
            compare1DB_DBSnapshot.setTitle( "Compare Database to Snapshot" );
            compare1DB_DBSnapshot.setVisible( true );
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        } else if ( input.getText().trim().equals( "3" )) {
        
            DBCompare1 compare1DB_DBSnapshot = new DBCompare1();
            compare1DB_DBSnapshot.setSize( 350 , 275 );
            compare1DB_DBSnapshot.setTitle( "Take Database Snapshot" );
            compare1DB_DBSnapshot.setButtonTxt( "Snapshot" );
            compare1DB_DBSnapshot.setVisible( true );
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
            
        } else {
        
            jLabel2.setText( "Please enter a number 1 to 3.");
        }
    }//GEN-LAST:event_jContinueMouseClicked
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DB_Diff_Checker_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DB_Diff_Checker_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DB_Diff_Checker_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DB_Diff_Checker_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DB_Diff_Checker_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Start;
    private javax.swing.JTextField input;
    private javax.swing.JButton jContinue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}